scorecard:
  plugins:
    - basic:
        namespace: default
        cr-manifest:
          - deploy/examples/lvmdriver.yaml
    - olm:
        namespace: default
        cr-manifest:
          - deploy/examples/lvmdriver.yaml
        csv-path: deploy/olm-catalog/0.9.0/ember-csi-operator.v0.9.0.clusterserviceversion.yaml
