scorecard:
  plugins:
    - basic:
        namespace: default
        cr-manifest:
          - deploy/examples/lvmdriver.yaml
    - olm:
        namespace: default
        cr-manifest:
          - deploy/examples/lvmdriver.yaml
        csv-path: deploy/olm-catalog/4.4.0/ember-csi-operator.v4.4.0.clusterserviceversion.yaml
