---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ember-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # my-ceph-sc.ember-csi.io for CSI spec >= 1.0
  storageClassName: io.ember-csi.my-ceph-sc
