apiVersion: "ember-csi.io/v1alpha1"
kind: "EmberCSI"
metadata:
  name: "xtremio"
spec:
  size: 1
  backend: xtremio
  config:
    envVars:
      X_CSI_PERSISTENCE_CONFIG:       '{"storage":"crd"}'
      X_CSI_BACKEND_CONFIG :          '{"volume_backend_name":"xtremio","volume_driver":"cinder.volume.drivers.dell_emc.xtremio.XtremIOISCSIDriver","san_ip":"1.2.3.4","xtremio_cluster_name":"exampleclustername","san_login":"someusername","san_password":"somesecretpassword"}'

