apiVersion: apps/v1
kind: Deployment
metadata:
  name: ember-csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ember-csi-operator
  template:
    metadata:
      labels:
        name: ember-csi-operator
    spec:
      containers:
        - name: ember-csi-operator
          image: quay.io/kirankt/ember-csi-operator:v0.0.2
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ember-csi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "ember-csi-operator"
