kind: ConfigMap
apiVersion: v1
metadata:
  name: ember-csi-operator
  namespace: openshift-operator-lifecycle-manager
data:
  customResourceDefinitions: |-
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: embercsis.ember-csi.io
      spec:
        group: ember-csi.io
        names:
          kind: EmberCSI
          listKind: EmberCSIList
          plural: embercsis
          singular: embercsi
        scope: Namespaced
        version: v1alpha1

  clusterServiceVersions: |-
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: embercsi.v0.0.2
        annotations:
          tectonic-visibility: ocs
      spec:
        displayName: Ember-CSI
        description: |-
           Multi-vendor CSI plugin driver supporting over 80 storage drivers in a single plugin to provide block and mount storage to Container Orchestration systems
        keywords: ['Ember-CSI', 'CSI']
        maintainers:
        - name: Red Hat
          email: geguileo@redhat.com
        - name: Red Hat
          email: kthyagar@redhat.com
        provider:
          name: Red Hat
        labels:
          operated-by: io.ember-csi
        selector:
          matchLabels:
            operated-by: io.ember-csi
        links:
        - name: Learn more about the project
          url: http://ember-csi.io/
        - name: Documentation
          url: http://readthedocs.org/projects/ember-csi/
        - name: Ember-CSI Source Code
          url: https://github.com/akrog/ember-csi
        - name: Ember-CSI Operator Source Code
          url: https://github.com/kirankt/ember-csi-operator
        version: 0.0.2
        maturity: alpha
        displayName: EmberCSI
        labels:
          olm-owner-enterprise-app: ember-csi-operator
          olm-status-descriptors: embercsi.v0.0.2

        install:
          strategy: deployment
          spec:
            permissions:
            - serviceAccountName: ember-csi-operator
              rules:
              - apiGroups:
                - ember-csi.io
                resources:
                - "*"
                verbs:
                - "*"
              - apiGroups:
                - rbac.authorization.k8s.io
                resources:
                - role
                - rolebindings
                - serviceaccounts
                verbs:
                - get
                - create
                - delete
                - patch
                - update
              - apiGroups:
                - ""
                resources:
                - serviceaccounts
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                verbs:
                - "*"
              - apiGroups:
                - apps
                resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
                verbs:
                - "*"
            clusterPermissions:
            - serviceAccountName: ember-csi-operator
              rules:
              - apiGroups:
                - ember-csi.io
                resources:
                - "*"
                verbs:
                - "*"
              - apiGroups:
                - rbac.authorization.k8s.io
                resources:
                - clusterrole
                - clusterrolebindings
                - role
                - rolebindings
                - serviceaccounts
                verbs:
                - get
                - create
                - delete
                - patch
                - update
              - apiGroups:
                - apiextensions.k8s.io
                resources:
                - customresourcedefinitions
                verbs:
                - list
                - create
              - apiGroups:
                - ""
                resources:
                - nodes
                verbs:
                - get
                - list
                - watch
              - apiGroups:
                - ""
                resources:
                - secrets
                verbs:
                - get
                - list
              - apiGroups:
                - ""
                resources:
                - persistentvolumes
                verbs:
                - create
                - delete
                - list
                - get
                - watch
                - update
              - apiGroups:
                - ""
                resources:
                - persistentvolumeclaims
                verbs:
                - get
                - list
                - watch
                - update
              - apiGroups:
                - storage.k8s.io
                resources:
                - volumeattachments
                verbs:
                - get
                - list
                - watch
                - update
                - delete
                - create
              - apiGroups:
                - storage.k8s.io
                resources:
                - storageclasses
                verbs:
                - create
                - get
                - list
                - watch
                - update
                - delete
            deployments:
            - name: ember-csi-operator
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: ember-csi-operator
                template:
                  metadata:
                    labels:
                      app: ember-csi-operator
                  spec:
                    containers:
                      - name: ember-csi-operator-olm-owned
                        image: quay.io/kirankt/ember-csi-operator:v0.0.2
                        command:
                        - ember-csi-operator
                        imagePullPolicy: Always
                        env:
                        - name: WATCH_NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                        - name: OPERATOR_NAME
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.name
                    restartPolicy: Always
                    terminationGracePeriodSeconds: 5
                    serviceAccountName: ember-csi-operator
                    serviceAccount: ember-csi-operator
        customresourcedefinitions:
          owned:
          - name: embercsis.ember-csi.io
            version: v1alpha1
            kind: EmberCSI
            displayName: EmberCSI Application
            description: Represents an instance of a EmberCSI application


  packages: |-
    - packageName: embercsi
      channels:
      - name: alpha
        currentCSV: embercsi.v0.0.2
