---
apiVersion: v1
kind: Namespace
metadata:
  name: ember-csi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ember-csi-operator
  namespace: ember-csi

---
# Create an SCC for OCP
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ember-csi-scc
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:ember-csi:ember-csi-operator
groups: []
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- nfs
- persistentVolumeClaim
- projected
- secret
